# Generated by Django 5.2.13 on 2026-05-01 09:11

from django.db import migrations, models


def normalize_payment_statuses(apps, schema_editor):
    Order = apps.get_model("shop", "Order")
    Order.objects.filter(payment_status="COD").update(payment_status="PENDING")


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_populate_tracking_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Thanh toán khi nhận hàng'), ('BANK_TRANSFER', 'Chuyển khoản ngân hàng'), ('MOMO', 'Ví MoMo'), ('ZALOPAY', 'Ví ZaloPay'), ('VNPAY', 'VNPay')], default='COD', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='province',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='street_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='ward',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('PAID', 'Đã thanh toán')], default='PENDING', max_length=10),
        ),
        migrations.RunPython(normalize_payment_statuses, migrations.RunPython.noop),
    ]
