# Generated by Django 5.2.13 on 2026-05-03 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_order_delivery_latitude_order_delivery_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_payment_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="shop.product",
            ),
        ),
    ]
