# Generated by Django 5.2.13 on 2026-05-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_customer_payment_notified_at_and_protect_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Khách hàng'), ('STAFF', 'Nhân viên'), ('OPERATOR', 'Nhân viên vận hành'), ('MANAGER', 'Quản lý')], default='CUSTOMER', max_length=20),
        ),
    ]
