# Generated by Django 5.2.13 on 2026-05-04 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_paid_at_alter_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid_at',
        ),
    ]
